# Generated by Django 5.0.6 on 2024-06-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='executor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.executordata'),
        ),
    ]
