# Generated by Django 5.0.6 on 2024-06-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='executor_id',
            new_name='executor',
        ),
    ]
