# Generated by Django 5.0.6 on 2024-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_category_id_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='adress',
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
