# Generated by Django 5.0.6 on 2024-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_service_adress_service_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/service'),
        ),
    ]
