# Generated by Django 5.0.6 on 2024-06-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
