# Generated by Django 5.0.6 on 2024-06-28 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_service_deleted'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city'),
        ),
    ]
