# Generated by Django 5.0.6 on 2024-06-30 14:54

import imageutils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_service_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=imageutils.fields.CustomImageField(blank=True, null=True, upload_to='static/category'),
        ),
    ]
