# Generated by Django 5.0.6 on 2024-06-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='timetable',
        ),
    ]
