# Generated by Django 5.0.6 on 2024-06-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_service_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='timetable',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
